FROM abiosoft/caddy:0.11.0                                                      
                                                                                
COPY ./compose/caddy/Caddyfile /etc/Caddyfile
RUN mkdir -p /voyant/corpora
